### ISSUE TITLE
USER STORY: Publish a poll

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/love-running#4]
As an **admin** I can **publish a poll** so that **I get useful user feedback**

## Acceptance criteria:

a. Adding a poll must be quick and easy
b. Polls should allow all relevant options
c. Results should be easy to view and compare without manual calculation

## Tasks

- [ ] Update the admin module view to include an expiry date selector in the poll design
- [ ] Create a function that checks the expiry date
- [ ] Create a job to check expired polls every day at 34:59 and Hide them
- [ ] Update the controller funciton
- [ ] Update unit test scripts
- [ ] Test the functionality
