### ISSUE TITLE
USER STORY: Create a Poll

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/love-running#6]
As an **admin** I can **create polls** in order to **get specific input from users**

## Acceptance Criteria:

a. Creating a poll must be easy
b. The module must be flexible and let med design different polls

## Tasks

- [x] Create a function for creating new polls
- [x] Make the design modular
- [x] Update the admin view
- [x] Test the functionality
